version = 1

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["bootstrap/app.php"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true